name: Build dependency cache on main branch
permissions:
  contents: read

on:
  push:
    branches: [main, master]
    paths:
      - '.github/workflows/cache-hubval-deps.yaml'
  schedule:
    - cron: "10 0 * * *"

jobs:
  build-deps-cache-on-main:
    if: ${{ github.repository_owner == 'reichlab' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@473c68190595b311a74f208fba61a8d8c0d4c247  #v2.11.1
        with:
          install-r: true
          use-public-rspm: true
          extra-repositories: 'https://hubverse-org.r-universe.dev'

      - name: Update R
        run: |
          sudo apt-get update

      - uses: r-lib/actions/setup-r-dependencies@473c68190595b311a74f208fba61a8d8c0d4c247  #v2.11.1
        with:
          packages: |
            any::hubValidations
            any::sessioninfo
